# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

simulator = "iPhone 12 Pro"

all_modules_schemes = [
  'Domain-Example',
  'Networking-Example',
  'Branding-Example',
  'UIComponents-Example'
]

platform :ios do

  ### TESTS ###
  desc "Runs all unit and UI tests and tests if all modules are buildable"
  desc "Use `fastlane test`"

  lane :test do |options|

    # Check if all modules are buildable
    all_modules_schemes.each do |scheme|
      UI.message "Testing if module #{scheme} is buildable"
      scan(
        scheme: scheme,
        device: simulator,
        build_for_testing: true
      )
    end

    # Run all unit and UI tests, and test if App is buildable
    scan(
      scheme: "CryptoPairs",
      device: simulator
    )

  end
end
